from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "saidas"

FONTE_TEXTO = "Calibri"
FONTE_TITULO = "Arial"

COR_TITULO = "1F3864"
COR_LINHA = "8EAADB"
COR_TEXTO = "262626"
COR_CONTATO = "595959"
COR_DATA = "7F7F7F"

TAM_NOME = 16
TAM_CONTATO = 10
TAM_SECAO = 9
TAM_ROTULO = 8.5
TAM_DATA = 8
TAM_TEXTO = 10

MARGEM_SUPERIOR = 0.55
MARGEM_INFERIOR = 0.5
MARGEM_ESQUERDA = 0.5
MARGEM_DIREITA = 0.5

RECUO_BULLET_TEXTO = 0.17
RECUO_BULLET_MARCADOR = 0.12
